(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem('kz-'+k))??d}catch{return d}};
const put=(k,v)=>localStorage.setItem('kz-'+k,JSON.stringify(v));
const agentName=w=>w==='chatgpt'?'ChatGPT':'Claude';
function route(t){if(t.worker&&t.worker!=='auto')return t.worker;let text=String(t.text||'');return text.length>220||/recherch|analys|datei|github|programm|code|video|plan|strategie|mehrere|komplex/i.test(text)?'chatgpt':'claude'}
function desks(){let tasks=get('tasks',[]),sessions=get('sessions',[]);return ['claude','chatgpt'].map(type=>{let mine=tasks.filter(t=>t.state==='work'&&route(t)===type),s=sessions.find(x=>x.type===type),waiting=mine.find(t=>t.waiting);return{key:type,name:agentName(type),state:waiting?'wait':mine.length?'work':(s?.state==='ready'?'work':'off'),task:waiting||mine[0]||null,count:mine.length}})}
function deskHtml(d){let state=d.state==='work'?'arbeitet':d.state==='wait'?'wartet':'frei';return `<div class="panel kz-agent-desk" data-desk="${d.key}" tabindex="0"><div class="row"><b>${d.name}</b><span>${state}</span></div><p>${d.task?esc(d.task.text):'Keine offene Aufgabe.'}</p>${d.count?`<small>${d.count} offene Aufgabe${d.count===1?'':'n'}</small>`:''}${d.state==='wait'?`<div class="row"><button data-allow="${d.key}">Erlauben</button><button data-look="${d.key}">Ansehen</button></div>`:''}</div>`}
function inject(){if(typeof active==='undefined'||active!=='buero')return;let page=document.querySelector('#main .page');if(!page||page.querySelector('#agentDesks'))return;let ds=desks(),wrap=document.createElement('div');wrap.id='agentDesks';wrap.innerHTML=`<div class="panel"><b>Agenten</b><p>${ds.filter(x=>x.state==='work').length} arbeiten · ${ds.filter(x=>x.state==='wait').length} wartet</p></div><div class="cards">${ds.map(deskHtml).join('')}</div>`;let system=page.querySelector('.panel');system?.after(wrap);bind(wrap)}
function bind(root){root.querySelectorAll('[data-desk]').forEach(el=>{el.ondblclick=()=>showNah(el.dataset.desk)});root.querySelectorAll('[data-look]').forEach(b=>b.onclick=e=>{e.stopPropagation();showNah(b.dataset.look)});root.querySelectorAll('[data-allow]').forEach(b=>b.onclick=e=>{e.stopPropagation();let tasks=get('tasks',[]),d=desks().find(x=>x.key===b.dataset.allow);if(d?.key==='chatgpt')return;if(d?.task){let t=tasks.find(x=>x.at===d.task.at&&x.text===d.task.text);if(t){t.waiting=false;t.allowed=true;put('tasks',tasks);if(typeof log==='function')log('Freigabe erteilt: '+d.name);if(typeof render==='function')render()}}})}
function showNah(key){let d=desks().find(x=>x.key===key);if(!d)return;let page=document.querySelector('#main');page.innerHTML=`<section class="page"><span class="eyebrow">Nahaufnahme</span><h1>${d.name}</h1><div class="panel"><b>Status</b><p>${d.state==='work'?'arbeitet':d.state==='wait'?'wartet auf Freigabe':'frei'}</p></div><div class="panel"><b>Aktuelle Aufgabe</b><p>${d.task?esc(d.task.text):'Keine offene Aufgabe.'}</p></div><button id="nahBack">← Büro</button></section>`;document.querySelector('#nahBack').onclick=()=>{if(typeof active!=='undefined')active='buero';if(typeof render==='function')render()}}
setInterval(inject,350);window.addEventListener('storage',inject);
})();