(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const agentName=w=>KZRegistry.agents.find(a=>a.id===w)?.name||w;
function desks(){return KZRegistry.agents.map(agent=>{const mine=tasks.filter(t=>t.worker===agent.id),working=mine.find(t=>t.state==='work'),waiting=mine.find(t=>t.state==='wartet_auf_freigabe');return {key:agent.id,name:agent.name,state:working?'work':waiting?'wait':'off',task:working||waiting||mine[0]||null,count:mine.filter(t=>['work','wait','wartet_auf_freigabe'].includes(t.state)).length}})}
function deskHtml(d){let state=d.state==='work'?'arbeitet':d.state==='wait'?'wartet':'frei';return `<div class="panel kz-agent-desk" data-desk="${d.key}" tabindex="0"><div class="row"><b>${d.name}</b><span>${state}</span></div><p>${d.task?esc(d.task.text):'Keine offene Aufgabe.'}</p>${d.count?`<small>${d.count} offene Aufgabe${d.count===1?'':'n'}</small>`:''}${d.state==='wait'?`<div class="row"><button data-allow="${d.key}">Erlauben</button><button data-look="${d.key}">Ansehen</button></div>`:''}</div>`}
function inject(){if(typeof active==='undefined'||active!=='buero')return;let page=document.querySelector('#main .page');if(!page||page.querySelector('#agentDesks'))return;let ds=desks(),wrap=document.createElement('div');wrap.id='agentDesks';wrap.innerHTML=`<div class="panel"><b>Agenten</b><p>${ds.filter(x=>x.state==='work').length} arbeiten · ${ds.filter(x=>x.state==='wait').length} wartet</p></div><div class="cards">${ds.map(deskHtml).join('')}</div>`;let system=page.querySelector('.panel');system?.after(wrap);bind(wrap)}
function bind(root){root.querySelectorAll('[data-desk]').forEach(el=>{el.ondblclick=()=>showNah(el.dataset.desk)});root.querySelectorAll('[data-look]').forEach(b=>b.onclick=e=>{e.stopPropagation();showNah(b.dataset.look)});root.querySelectorAll('[data-allow]').forEach(b=>b.onclick=e=>{e.stopPropagation();const d=desks().find(x=>x.key===b.dataset.allow);if(d?.task)approveTask(d.task.id)})}
function showNah(key){let d=desks().find(x=>x.key===key);if(!d)return;let page=document.querySelector('#main');page.innerHTML=`<section class="page"><span class="eyebrow">Nahaufnahme</span><h1>${d.name}</h1><div class="panel"><b>Status</b><p>${d.state==='work'?'arbeitet':d.state==='wait'?'wartet auf Freigabe':'frei'}</p></div><div class="panel"><b>Aktuelle Aufgabe</b><p>${d.task?esc(d.task.text):'Keine offene Aufgabe.'}</p>${d.task?taskOutput(d.task):''}</div><button id="nahBack">← Büro</button></section>`;page.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approveTask(b.dataset.approve));document.querySelector('#nahBack').onclick=()=>{if(typeof active!=='undefined')active='buero';if(typeof render==='function')render()}}
setInterval(inject,350);window.addEventListener('storage',inject);
})();