const sections=[['buero','Büro','Startseite: deine Agenten, Aufgaben und Zahlen auf einen Blick'],['auftrag','Auftrag','Aufgabe reinschreiben, der passende Agent übernimmt'],['werkbank','Werkbank','Mehrere Chats nebeneinander (Claude und Codex)'],['vorschau','Vorschau','Seiten, Bilder, Videos und Texte ansehen, die gerade entstehen'],['werkstatt','Werkstatt','Carousels prüfen und Videos schneiden'],['ablage','Ablage','Alles, was heute entstanden ist, plus Tagesverlauf'],['kanaele','Kanäle','Instagram, TikTok und YouTube: Zahlen und Reels'],['leads','Leads','Firmen finden, prüfen und nachfassen: dein Mini-CRM'],['mails','Mails','Mitglieder-Mails prüfen und freigeben'],['funde','Fundstücke','Neue Tools und Ideen von GitHub'],['skills','Skills','Alle Fähigkeiten von Claude, per Klick starten']];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem('kz-'+k))??d}catch{return d}}, save=(k,v)=>localStorage.setItem('kz-'+k,JSON.stringify(v));
let active='buero', sessions=load('sessions',[{id:crypto.randomUUID(),name:'claude',type:'claude',state:'off',messages:[]}]), tasks=load('tasks',[]), leads=load('leads',[]), activity=load('activity',[]), previews=load('previews',[]), briefing=load('briefing','');
function log(text){activity.unshift({at:new Date().toISOString(),text});activity=activity.slice(0,200);save('activity',activity)}
function renderNav(){const n=$('#nav');n.innerHTML='';sections.forEach(([id,name,desc])=>{let b=document.createElement('button');b.textContent=name;b.title=desc;b.className=id===active?'on':'';b.onclick=()=>{active=id;render()};n.appendChild(b)})}
const head=(id)=>{let s=sections.find(x=>x[0]===id);return `<span class="eyebrow">Kommandozentrale</span><h1>${s[1]}</h1><p>${s[2]}</p>`};
function render(){renderNav();let h=head(active);if(active==='buero')h+=`<div class="cards"><div class="panel"><b>Agenten / Sitzungen</b><strong>${sessions.length}</strong></div><div class="panel"><b>Aufgaben</b><strong>${tasks.filter(x=>!x.done).length}</strong></div><div class="panel"><b>Leads</b><strong>${leads.length}</strong></div></div><div class="panel"><b>Letzte Aktivität</b>${activity.slice(0,8).map(x=>`<p>${esc(new Date(x.at).toLocaleString('de-DE'))} · ${esc(x.text)}</p>`).join('')||'<p>Noch keine Aktivität.</p>'}</div>`;
if(active==='auftrag')h+=`<form class="panel form" id="taskForm"><label>Aufgabe<textarea name="text" required></textarea></label><button>Aufgabe anlegen</button></form><div class="panel"><b>Aufgaben</b>${tasks.map((x,i)=>`<div class="row"><button data-done="${i}">${x.done?'✓':'○'}</button><span class="${x.done?'done':''}">${esc(x.text)}</span></div>`).join('')||'<p>Keine Aufgaben.</p>'}</div>`;
if(active==='werkbank')h+=`<div class="panel"><b>Sitzungen</b>${sessions.map((x,i)=>`<div class="row"><span><b>${esc(x.name)}</b> · ${esc(x.type)}</span><button data-session="${i}">Öffnen</button></div>`).join('')}</div><button id="newSession">+ Neue Sitzung</button><div class="panel" id="sessionPane"></div>`;
if(active==='vorschau')h+=`<div class="panel"><b>Vorschau</b>${previews.map(x=>`<div class="preview"><b>${esc(x.name)}</b><pre>${esc(x.content)}</pre></div>`).join('')||'<p>Noch keine Inhalte in der Vorschau.</p>'}</div>`;
if(active==='werkstatt')h+=`<div class="panel"><b>Werkstatt</b><p>Das Desktop-Original startet hierfür lokale Video-/Python-Prozesse und ein lokales Cut-Cockpit. Auf iOS benötigt dieser Bereich den noch anzubindenden Ausführungsdienst; es wird keine Scheinverarbeitung angezeigt.</p></div>`;
if(active==='ablage')h+=`<div class="panel"><b>Tagesverlauf</b>${activity.map(x=>`<p>${esc(new Date(x.at).toLocaleString('de-DE'))} · ${esc(x.text)}</p>`).join('')||'<p>Leer.</p>'}</div>`;
if(active==='kanaele')h+=`<div class="panel"><b>Kanäle</b><p>Das Original liest Social-Daten aus lokalen Dateien und startet für Instagram-Auswertungen ein Python-Skript. Die mobile Oberfläche ist vorbereitet; echte Daten werden erst nach Anbindung des Ausführungsdienstes gezeigt.</p></div>`;
if(active==='leads')h+=`<form class="panel form" id="leadForm"><label>Firma<input name="firma" required></label><label>Ort<input name="ort"></label><label>Branche<input name="branche"></label><label>Website<input name="website"></label><label>Telefon<input name="telefon"></label><label>E-Mail<input name="mail" type="email"></label><label>Status<select name="status"><option>neu</option><option>kontaktiert</option><option>interessiert</option><option>termin</option><option>kunde</option><option>abgesagt</option></select></label><label>Nachfassen<input name="followup" type="date"></label><button>Lead speichern</button></form><div class="panel">${leads.map((x,i)=>`<div class="lead"><b>${esc(x.firma)}</b><span>${esc(x.ort)} · ${esc(x.branche)} · ${esc(x.status)}</span><span>${x.telefon?`<a href="tel:${esc(x.telefon)}">${esc(x.telefon)}</a>`:''} ${x.mail?`<a href="mailto:${esc(x.mail)}">${esc(x.mail)}</a>`:''}</span><button data-lead="${i}">Bearbeiten</button></div>`).join('')||'<p>Noch keine Leads.</p>'}</div>`;
if(active==='mails')h+=`<div class="panel"><b>Mails</b><p>Die Desktop-Version prüft lokale Mitglieder-Maildaten. Freigaben werden hier erst aktiviert, wenn dieselbe Datenquelle mobil erreichbar ist.</p></div>`;
if(active==='funde')h+=`<div class="panel"><b>Fundstücke</b><button id="loadGithub">↻ Jetzt laden</button><div id="githubResults"><p>GitHub-Suche wie im Original.</p></div></div>`;
if(active==='skills')h+=`<div class="panel"><b>Skills</b><p>Im Original werden Claude-Skills aus dem lokalen System geladen. Nach Anbindung des Claude-Ausführungsdienstes erscheinen hier dieselben Skills.</p></div>`;
$('#main').innerHTML=`<section class="page">${h}</section>`;bind();}
function bind(){let f=$('#taskForm');if(f)f.onsubmit=e=>{e.preventDefault();tasks.unshift({text:new FormData(f).get('text'),done:false,at:new Date().toISOString()});save('tasks',tasks);log('Aufgabe angelegt');render()};document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{let i=+b.dataset.done;tasks[i].done=!tasks[i].done;save('tasks',tasks);log('Aufgabe aktualisiert');render()});
let lf=$('#leadForm');if(lf)lf.onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(lf));leads.unshift(x);save('leads',leads);log('Lead gespeichert: '+x.firma);render()};document.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>{let i=+b.dataset.lead,x=leads[i],v=prompt('Status',x.status);if(v!==null){x.status=v;save('leads',leads);log('Lead aktualisiert: '+x.firma);render()}});
let ns=$('#newSession');if(ns)ns.onclick=()=>{let type=prompt('Sitzung: claude, codex oder agent','claude');if(!type)return;sessions.push({id:crypto.randomUUID(),name:type,type,state:'off',messages:[]});save('sessions',sessions);log('Sitzung angelegt: '+type);render()};document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>showSession(+b.dataset.session));
let gh=$('#loadGithub');if(gh)gh.onclick=loadGithub;}
function showSession(i){let x=sessions[i],p=$('#sessionPane');p.innerHTML=`<b>${esc(x.name)}</b><p>Die Sitzung ist angelegt. Claude/Codex wird erst als echte Sitzung gestartet, sobald der mobile Ausführungsdienst verbunden ist.</p><div>${x.messages.map(m=>`<p>${esc(m)}</p>`).join('')}</div>`}
async function loadGithub(){let out=$('#githubResults');out.innerHTML='<p>Lädt…</p>';try{let qs=['claude ai tools','ai video automation','social media automation'],all=[];for(let q of qs){let r=await fetch('https://api.github.com/search/repositories?q='+encodeURIComponent(q)+'&sort=stars&order=desc&per_page=5');if(!r.ok)throw Error('GitHub '+r.status);let j=await r.json();all.push(...j.items)}let uniq=[...new Map(all.map(x=>[x.full_name,x])).values()].slice(0,12);out.innerHTML=uniq.map(x=>`<p><a target="_blank" rel="noopener" href="${esc(x.html_url)}"><b>${esc(x.full_name)}</b></a><br>${esc(x.description||'')} · ★ ${x.stargazers_count}</p>`).join('');log('Fundstücke geladen')}catch(e){out.innerHTML='<p>GitHub nicht erreichbar.</p>'}}
$('#briefing').onclick=()=>{$('#main').innerHTML=`<section class="page"><span class="eyebrow">Briefing</span><h1>Dein Tagesplan von heute früh</h1><textarea id="briefText" class="bigtext" placeholder="Briefing">${esc(briefing)}</textarea><button id="saveBrief">Speichern</button></section>`;$('#saveBrief').onclick=()=>{briefing=$('#briefText').value;save('briefing',briefing);log('Briefing gespeichert')}};
$('#chat').onsubmit=e=>{e.preventDefault();let p=$('#prompt'),v=p.value.trim();if(!v)return;tasks.unshift({text:v,done:false,at:new Date().toISOString(),source:'chat'});save('tasks',tasks);log('Auftrag über Chat erfasst');p.value='';active='auftrag';render()};$('#plus').onclick=()=>{active='werkbank';render();$('#newSession')?.click()};
render();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');