const sections=[['buero','Büro','Startseite: deine Agenten, Aufgaben und Zahlen auf einen Blick'],['auftrag','Auftrag','Aufgabe reinschreiben, der passende Agent übernimmt'],['werkbank','Werkbank','Mehrere Chats nebeneinander (Claude und ChatGPT)'],['vorschau','Vorschau','Seiten, Bilder, Videos und Texte ansehen, die gerade entstehen'],['werkstatt','Werkstatt','Carousels prüfen und Videos schneiden'],['ablage','Ablage','Alles, was heute entstanden ist, plus Tagesverlauf'],['kanaele','Kanäle','Instagram, TikTok und YouTube: Zahlen und Reels'],['leads','Leads','Firmen finden, prüfen und nachfassen: dein Mini-CRM'],['mails','Mails','Mitglieder-Mails prüfen und freigeben'],['funde','Fundstücke','Neue Tools und Ideen von GitHub'],['skills','Skills','Alle Fähigkeiten der Arbeitsmaschine, per Klick starten']];
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem('kz-'+k))??d}catch{return d}},save=(k,v)=>localStorage.setItem('kz-'+k,JSON.stringify(v));
let active='buero',sessions=load('sessions',[{id:crypto.randomUUID(),name:'claude',type:'claude',state:'off',messages:[]},{id:crypto.randomUUID(),name:'ChatGPT',type:'chatgpt',state:'external',messages:[]}]),tasks=load('tasks',[]),leads=load('leads',[]),activity=load('activity',[]),previews=load('previews',[]),briefing=load('briefing',''),backend={online:false,capabilities:null};
function log(text){activity.unshift({at:new Date().toISOString(),text});activity=activity.slice(0,200);save('activity',activity)}
async function refreshBackend(){try{let h=await fetch('/api/health',{cache:'no-store'});if(!h.ok)throw Error();let c=await fetch('/api/capabilities',{cache:'no-store'});backend={online:true,capabilities:c.ok?await c.json():null}}catch{backend={online:false,capabilities:null}}if(active==='buero'||active==='werkbank'||active==='werkstatt'||active==='skills')render()}
function statusHtml(){let c=backend.capabilities;if(!backend.online)return '<span>Ausführungsdienst: nicht erreichbar</span>';if(!c)return '<span>Ausführungsdienst: verbunden</span>';return `<span>Ausführungsdienst: verbunden · Python ${c.python?'✓':'–'} · Git ${c.git?'✓':'–'} · FFmpeg ${c.ffmpeg?'✓':'–'} · Claude ${c.claude?'✓':'–'} · ChatGPT: Arbeitsmaschine</span>`}
function renderNav(){const n=$('#nav');n.innerHTML='';sections.forEach(([id,name,desc])=>{let b=document.createElement('button');b.textContent=name;b.title=desc;b.className=id===active?'on':'';b.onclick=()=>{active=id;render()};n.appendChild(b)})}
const head=id=>{let s=sections.find(x=>x[0]===id);return `<span class="eyebrow">Kommandozentrale</span><h1>${s[1]}</h1><p>${s[2]}</p>`};
function render(){renderNav();let h=head(active);if(active==='buero')h+=`<div class="panel"><b>System</b><p>${statusHtml()}</p><p>Rollen: Claude = einfache Fragen und Aufgaben · ChatGPT = Arbeitsmaschine. Keine kostenpflichtige API.</p></div><div class="cards"><div class="panel"><b>Agenten / Sitzungen</b><strong>${sessions.length}</strong></div><div class="panel"><b>Aufgaben</b><strong>${tasks.filter(x=>!x.done).length}</strong></div><div class="panel"><b>Leads</b><strong>${leads.length}</strong></div></div><div class="panel"><b>Letzte Aktivität</b>${activity.slice(0,8).map(x=>`<p>${esc(new Date(x.at).toLocaleString('de-DE'))} · ${esc(x.text)}</p>`).join('')||'<p>Noch keine Aktivität.</p>'}</div>`;
if(active==='auftrag')h+=`<form class="panel form" id="taskForm"><label>Aufgabe<textarea name="text" required></textarea></label><label>Bearbeitung<select name="worker"><option value="auto">Automatisch</option><option value="claude">Claude · einfach</option><option value="chatgpt">ChatGPT · Arbeitsmaschine</option></select></label><button>Aufgabe anlegen</button></form><div class="panel"><b>Aufgaben</b>${tasks.map((x,i)=>`<div class="row"><button data-done="${i}">${x.done?'✓':'○'}</button><span class="${x.done?'done':''}">${esc(x.text)}${x.worker?` · ${esc(x.worker)}`:''}</span></div>`).join('')||'<p>Keine Aufgaben.</p>'}</div>`;
if(active==='werkbank')h+=`<div class="panel"><b>Ausführungsdienst</b><p>${statusHtml()}</p><p>Claude und ChatGPT werden getrennt geführt. Es wird keine kostenpflichtige API verwendet.</p></div><div class="panel"><b>Sitzungen</b>${sessions.map((x,i)=>`<div class="row"><span><b>${esc(x.name)}</b> · ${esc(x.type)}</span><button data-session="${i}">Öffnen</button></div>`).join('')}</div><button id="newSession">+ Neue Sitzung</button><div class="panel" id="sessionPane"></div>`;
if(active==='vorschau')h+=`<div class="panel"><b>Vorschau</b>${previews.map(x=>`<div class="preview"><b>${esc(x.name)}</b><pre>${esc(x.content)}</pre></div>`).join('')||'<p>Noch keine Inhalte in der Vorschau.</p>'}</div>`;
if(active==='werkstatt')h+=`<div class="panel"><b>Werkstatt</b><p>${statusHtml()}</p><p>${backend.capabilities?.ffmpeg?'FFmpeg ist auf dem Ausführungsdienst verfügbar.':'Die Video-Verarbeitung benötigt FFmpeg auf dem Ausführungsdienst.'}</p></div>`;
if(active==='ablage')h+=`<div class="panel"><b>Tagesverlauf</b>${activity.map(x=>`<p>${esc(new Date(x.at).toLocaleString('de-DE'))} · ${esc(x.text)}</p>`).join('')||'<p>Leer.</p>'}</div>`;
if(active==='kanaele')h+=`<div class="panel"><b>Kanäle</b><p>Die vorhandenen Social-Datenquellen werden als nächster Funktionsblock an den Ausführungsdienst angebunden.</p></div>`;
if(active==='leads')h+=`<form class="panel form" id="leadForm"><label>Firma<input name="firma" required></label><label>Ort<input name="ort"></label><label>Branche<input name="branche"></label><label>Website<input name="website"></label><label>Telefon<input name="telefon"></label><label>E-Mail<input name="mail" type="email"></label><label>Status<select name="status"><option>neu</option><option>kontaktiert</option><option>interessiert</option><option>termin</option><option>kunde</option><option>abgesagt</option></select></label><label>Nachfassen<input name="followup" type="date"></label><button>Lead speichern</button></form><div class="panel">${leads.map((x,i)=>`<div class="lead"><b>${esc(x.firma)}</b><span>${esc(x.ort)} · ${esc(x.branche)} · ${esc(x.status)}</span><span>${x.telefon?`<a href="tel:${esc(x.telefon)}">${esc(x.telefon)}</a>`:''} ${x.mail?`<a href="mailto:${esc(x.mail)}">${esc(x.mail)}</a>`:''}</span><button data-lead="${i}">Bearbeiten</button></div>`).join('')||'<p>Noch keine Leads.</p>'}</div>`;
if(active==='mails')h+=`<div class="panel"><b>Mails</b><p>Die vorhandene Mitglieder-Maildatenquelle wird nach Übertragung der Originaldatenstruktur angebunden.</p></div>`;
if(active==='funde')h+=`<div class="panel"><b>Fundstücke</b><button id="loadGithub">↻ Jetzt laden</button><div id="githubResults"><p>GitHub-Suche wie im Original.</p></div></div>`;
if(active==='skills')h+=`<div class="panel"><b>Skills</b><p>${statusHtml()}</p><p>Arbeits-Skills werden ohne kostenpflichtige Modell-API angebunden.</p></div>`;
$('#main').innerHTML=`<section class="page">${h}</section>`;bind()}
function bind(){let f=$('#taskForm');if(f)f.onsubmit=e=>{e.preventDefault();let d=new FormData(f);tasks.unshift({text:d.get('text'),worker:d.get('worker'),done:false,at:new Date().toISOString()});save('tasks',tasks);log('Aufgabe angelegt');render()};document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{let i=+b.dataset.done;tasks[i].done=!tasks[i].done;save('tasks',tasks);log('Aufgabe aktualisiert');render()});let lf=$('#leadForm');if(lf)lf.onsubmit=e=>{e.preventDefault();let x=Object.fromEntries(new FormData(lf));leads.unshift(x);save('leads',leads);log('Lead gespeichert: '+x.firma);render()};document.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>{let i=+b.dataset.lead,x=leads[i],v=prompt('Status',x.status);if(v!==null){x.status=v;save('leads',leads);log('Lead aktualisiert: '+x.firma);render()}});let ns=$('#newSession');if(ns)ns.onclick=()=>{let type=prompt('Sitzung: claude, chatgpt oder agent','claude');if(!type)return;sessions.push({id:crypto.randomUUID(),name:type==='chatgpt'?'ChatGPT':type,type,state:type==='chatgpt'?'external':'off',messages:[]});save('sessions',sessions);log('Sitzung angelegt: '+type);render()};document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>showSession(+b.dataset.session));let gh=$('#loadGithub');if(gh)gh.onclick=loadGithub}
async function showSession(i){let x=sessions[i],p=$('#sessionPane');if(x.type==='chatgpt'){p.innerHTML=`<b>ChatGPT · Arbeitsmaschine</b><p>Diese Rolle nutzt keine kostenpflichtige API. Arbeitsaufträge werden für die bestehende ChatGPT-/Codex-Nutzung geführt.</p>`;return}p.innerHTML=`<b>${esc(x.name)}</b><p>Sitzung wird geprüft…</p>`;if(x.type!=='claude'){p.innerHTML=`<b>${esc(x.name)}</b><p>Agent-Sitzung angelegt.</p>`;return}try{let r=await fetch('/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:x.type})}),j=await r.json();x.state=r.ok?'ready':'off';save('sessions',sessions);p.innerHTML=`<b>${esc(x.name)}</b><p>${r.ok?'Sitzungsdienst bereit.':esc(j.error||'Sitzung nicht verfügbar.')}</p>`}catch{p.innerHTML=`<b>${esc(x.name)}</b><p>Ausführungsdienst nicht erreichbar.</p>`}}
async function loadGithub(){let out=$('#githubResults');out.innerHTML='<p>Lädt…</p>';try{let qs=['claude ai tools','ai video automation','social media automation'],all=[];for(let q of qs){let r=await fetch('https://api.github.com/search/repositories?q='+encodeURIComponent(q)+'&sort=stars&order=desc&per_page=5');if(!r.ok)throw Error('GitHub '+r.status);let j=await r.json();all.push(...j.items)}let uniq=[...new Map(all.map(x=>[x.full_name,x])).values()].slice(0,12);out.innerHTML=uniq.map(x=>`<p><a target="_blank" rel="noopener" href="${esc(x.html_url)}"><b>${esc(x.full_name)}</b></a><br>${esc(x.description||'')} · ★ ${x.stargazers_count}</p>`).join('');log('Fundstücke geladen')}catch{out.innerHTML='<p>GitHub nicht erreichbar.</p>'}}
function showHelp(){let rows=sections.map(([id,n,d])=>`<button class="panel" data-help-go="${id}"><b>${esc(n)}</b><br><span>${esc(d)}</span></button>`).join('');$('#main').innerHTML=`<section class="page"><span class="eyebrow">Hilfe</span><h1>Was ist wo?</h1>${rows}<div class="panel"><b>Die wichtigsten Handgriffe</b><p>· Unten im Chat schreiben: dein Hauptweg für Aufgaben.</p><p>· „+“ in der Chat-Leiste: neue Sitzung mit Claude, ChatGPT oder einem Agenten.</p><p>· Briefing: dein Tagesplan von heute früh.</p></div></section>`;document.querySelectorAll('[data-help-go]').forEach(b=>b.onclick=()=>{active=b.dataset.helpGo;render()})}
$('#briefing').onclick=()=>{$('#main').innerHTML=`<section class="page"><span class="eyebrow">Briefing</span><h1>Dein Tagesplan von heute früh</h1><textarea id="briefText" class="bigtext" placeholder="Briefing">${esc(briefing)}</textarea><button id="saveBrief">Speichern</button></section>`;$('#saveBrief').onclick=()=>{briefing=$('#briefText').value;save('briefing',briefing);log('Briefing gespeichert')}};
$('#help').onclick=showHelp;
$('#chat').onsubmit=e=>{e.preventDefault();let p=$('#prompt'),v=p.value.trim();if(!v)return;tasks.unshift({text:v,worker:'auto',done:false,at:new Date().toISOString(),source:'chat'});save('tasks',tasks);log('Auftrag über Chat erfasst');p.value='';active='auftrag';render()};$('#plus').onclick=()=>{active='werkbank';render();$('#newSession')?.click()};
render();refreshBackend();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');