import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {homedir} from 'node:os';
import {TaskStore,redactSecrets} from './task-store.js';
import {TaskService} from './task-service.js';
import {CloudTaskPersistence,attachCloudPersistence} from './cloud-task-persistence.js';
import './registry.js';
const root=path.dirname(fileURLToPath(import.meta.url)),port=process.env.PORT||3000;
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))};
const body=req=>new Promise((ok,no)=>{let d='',size=0;req.on('data',c=>{size+=c.length;if(size>65536){no(Object.assign(Error('Anfrage zu groß'),{status:413}));req.resume();return}d+=c});req.on('error',no);req.on('aborted',()=>no(Error('Anfrage abgebrochen')));req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch{no(Object.assign(Error('Ungültiges JSON'),{status:400}))}})});
const envClean=()=>{let e={...process.env,OPENAI_API_KEY:'',ANTHROPIC_API_KEY:'',NO_COLOR:'1',TERM:'dumb',CI:'0',CLICOLOR:'0',FORCE_COLOR:'0'};if(!e.CODEX_HOME)e.CODEX_HOME=path.join(homedir(),'.codex');return e};
const toolNames=new Set(['codex','claude','git','node','python','python3','ffmpeg']);
function executable(cmd){if(!toolNames.has(cmd))return null;if(cmd==='node')return process.execPath;const names=cmd==='python'||cmd==='python3'?['python3','python']:[cmd];const dirs=(process.env.PATH||process.env.Path||'').split(path.delimiter).filter(Boolean);for(const name of names)for(const dir of dirs)for(const ext of process.platform==='win32'?['.exe','.com']:['']){const file=path.resolve(dir.replace(/^"|"$/g,''),name+ext);try{if(fs.statSync(file).isFile()){fs.accessSync(file,process.platform==='win32'?fs.constants.F_OK:fs.constants.X_OK);return file}}catch{}}return null}
const runningProcesses=new Set();
const run=(cmd,args=[],cwd=root,timeout=15000)=>new Promise(resolve=>{let file=executable(cmd);if(!file)return resolve({ok:false,error:'Programm nicht gefunden: '+cmd,stdout:'',stderr:''});let p=spawn(process.execPath,[path.join(root,'process-runner.js'),file,JSON.stringify(args)],{cwd,env:envClean(),shell:false,stdio:['ignore','pipe','pipe','ipc']}),out='',err='',done=false;p.stdout?.setEncoding('utf8');p.stderr?.setEncoding('utf8');runningProcesses.add(p);p.on('close',()=>runningProcesses.delete(p));let finish=r=>{if(done)return;done=true;clearTimeout(timer);try{if(p.connected)p.send({type:'stop'},()=>{});else p.kill('SIGTERM')}catch{}resolve(r)};p.stdout?.on('data',d=>{out+=d;if(out.length>2000000)finish({ok:false,error:'Codex-Ausgabe zu groß',stdout:'',stderr:''})});p.stderr?.on('data',d=>{err=(err+d).slice(-16000)});p.on('error',e=>finish({ok:false,error:e.message,stdout:out,stderr:err}));p.on('close',code=>finish({ok:code===0,code,stdout:out,stderr:err}));let timer=setTimeout(()=>finish({ok:false,timeout:true,stdout:out,stderr:err}),timeout)});
const present=async c=>Boolean(executable(c));const clean=s=>String(s||'').replace(/\x1B(?:[@-Z\\-_]|\[[0-?]*[ -\/]*[@-~])/g,'').replace(/\r/g,'').trim().slice(-16000);const authText=r=>clean(String((r.stdout||'')+'\n'+(r.stderr||'')));
const loginJobs=new Map();
async function authStatus(type){if(type==='chatgpt'){if(!await present('codex'))return {installed:false,connected:false};let r=await run('codex',['login','status'],root,8000);return {installed:true,connected:r.ok&&authText(r).includes('Logged in using ChatGPT'),detail:authText(r)}}if(type==='claude'){if(!await present('claude'))return {installed:false,connected:false};let r=await run('claude',['auth','status'],root,8000);return {installed:true,connected:r.ok,detail:authText(r)}}return {installed:false,connected:false}}
async function diagnostics(){if(!await present('codex'))return {installed:false};let v=await run('codex',['--version'],root,8000),h=await run('codex',['login','--help'],root,8000);return {installed:true,version:authText(v),deviceAuthSupported:/device-auth/.test(authText(h)),loginHelp:authText(h).slice(0,3000)}}
async function aiState(){let chatgpt=await authStatus('chatgpt'),claude=await authStatus('claude');return {ok:true,paidApi:false,chatgpt:{supported:true,...chatgpt,mode:'chatgpt-plan-codex',loginAvailable:chatgpt.installed},claude:{supported:true,...claude,mode:'claude-pro-max-code',loginAvailable:claude.installed,note:'Claude bleibt optional und kann nach einem Pro/Max-Upgrade angemeldet werden.'}}}
function jobView(type){let j=loginJobs.get(type);if(!j)return {running:false,output:''};return {running:j.running,finished:j.finished,code:j.code,output:clean(j.output),started:j.started}}
function waitForOutput(job,ms=10000){return new Promise(resolve=>{let start=Date.now(),t=setInterval(()=>{if(clean(job.output)||!job.running||Date.now()-start>=ms){clearInterval(t);resolve()}},150)})}
async function startLogin(type){if(type==='chatgpt'){let d=await diagnostics();if(!d.installed)return {ok:false,error:'Codex CLI ist noch nicht installiert.'};if(!d.deviceAuthSupported)return {ok:false,error:'Die installierte Codex-Version unterstützt --device-auth nicht.',diagnostics:d};let old=loginJobs.get(type);if(old?.running)return {ok:true,type,flow:'device-auth',diagnostics:d,...jobView(type)};let job={running:true,finished:false,code:null,output:'',started:Date.now()},p=spawn(executable('codex'),['login','--device-auth'],{cwd:root,env:envClean(),shell:false,stdio:['ignore','pipe','pipe']});job.process=p;loginJobs.set(type,job);p.stdout.setEncoding('utf8');p.stderr.setEncoding('utf8');p.stdout.on('data',d=>job.output+=d);p.stderr.on('data',d=>job.output+=d);p.on('error',e=>{job.output+='\n'+e.message;job.running=false;job.finished=true});p.on('close',code=>{job.code=code;job.running=false;job.finished=true});await waitForOutput(job,10000);let view=jobView(type);if(!view.output&&job.running){job.output+='\nCodex läuft, hat aber noch keinen Gerätecode ausgegeben.';view=jobView(type)}return {ok:true,type,flow:'device-auth',diagnostics:d,...view}}if(type==='claude'){if(!await present('claude'))return {ok:false,error:'Claude Code ist noch nicht installiert.'};let r=await run('claude',['auth','login'],root,12000);return {ok:r.ok||r.timeout,type,flow:'browser-login',output:authText(r)}}return {ok:false,error:'Unbekannter Anbieter'}}
const safeError=text=>redactSecrets(clean(text));
const store=new TaskStore(root,process.env.KZ_DATA_DIR||'.kz-data');
const requestedTimeout=Number(process.env.KZ_EXECUTION_TIMEOUT_MS||120000);const executionTimeout=Number.isFinite(requestedTimeout)?Math.min(120000,Math.max(1000,requestedTimeout)):120000;
let cloudPersistence=null;let cloudPersistenceError='';
try{cloudPersistence=new CloudTaskPersistence()}catch(e){cloudPersistenceError=safeError(e.message)}
const tasksService=new TaskService({store,run,authStatus,root,timeout:executionTimeout});
if(cloudPersistence)attachCloudPersistence(tasksService,cloudPersistence);
async function registryState(){const ai=await aiState();return {agents:globalThis.KZRegistry.agents.map(a=>({...a,...ai[a.id],available:a.executable&&!!ai[a.id]?.connected})),skills:globalThis.KZRegistry.skills.map(s=>({...s,available:!!ai[s.agent]?.connected})),tools:await Promise.all(globalThis.KZRegistry.tools.map(async id=>({id,installed:await present(id),executable:false})))} }
function requireJson(req){if(!String(req.headers['content-type']||'').startsWith('application/json'))throw Object.assign(Error('JSON erforderlich'),{status:415})}
async function taskApi(req,res,u){
  if(u.pathname==='/api/tasks'){
    if(req.method==='GET')return json(res,200,{ok:true,tasks:tasksService.list(),cloud:{configured:!!cloudPersistence}});
    if(req.method!=='POST')return json(res,405,{ok:false,error:'GET oder POST erforderlich'});
    requireJson(req);const job=await tasksService.create(await body(req));return json(res,job.state==='error'?502:job.state==='done'?200:202,job);
  }
  const match=/^\/api\/tasks\/([^/]+)(\/approve)?$/.exec(u.pathname);if(!match)return json(res,400,{ok:false,error:'Ungültige Auftrags-ID'});
  if(match[2]){if(req.method!=='POST')return json(res,405,{ok:false,error:'POST erforderlich'});requireJson(req);const input=await body(req);return json(res,200,tasksService.approve(match[1],input?.approved));}
  if(req.method!=='GET')return json(res,405,{ok:false,error:'GET erforderlich'});
  if(cloudPersistence){const cloud=await cloudPersistence.get(match[1]);if(cloud)return json(res,200,{...cloud,result:cloud.result_text,cloudPersisted:true});}
  return json(res,200,tasksService.get(match[1]));
}
async function api(req,res,u){if(u.pathname==='/api/registry')return json(res,200,{ok:true,...await registryState()});if(u.pathname==='/api/tasks'||u.pathname.startsWith('/api/tasks/'))return taskApi(req,res,u);if(u.pathname==='/api/health')return json(res,200,{ok:true,service:'kommandozentrale',cloud:{configured:!!cloudPersistence,error:cloudPersistence?null:cloudPersistenceError}});if(u.pathname==='/api/diagnostics')return json(res,200,{ok:true,codex:await diagnostics()});if(u.pathname==='/api/capabilities'){let a=await aiState();return json(res,200,{node:true,python:await present('python3'),git:await present('git'),ffmpeg:await present('ffmpeg'),claude:a.claude.installed,codex:a.chatgpt.installed,claudeConnected:a.claude.connected,codexConnected:a.chatgpt.connected,paidApi:false,cloudPersistence:!!cloudPersistence})}if(u.pathname==='/api/ai-status')return json(res,200,await aiState());if(u.pathname==='/api/auth/start'&&req.method==='POST'){let b=await body(req),r=await startLogin(String(b.type||''));return json(res,r.ok?200:503,r)}if(u.pathname==='/api/auth/status'){let type=String(u.searchParams.get('type')||'chatgpt'),auth=await authStatus(type);return json(res,200,{ok:true,type,...auth,...jobView(type)})}return json(res,404,{ok:false,error:'Nicht gefunden'})}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.md':'text/markdown; charset=utf-8'};const publicFiles=new Set(['index.html','styles.css','app.js','agent-layer.js','registry.js','sw.js','manifest.webmanifest']);const realRoot=fs.realpathSync(root);
function publicFile(pathname){let rel;try{rel=pathname==='/'?'index.html':decodeURIComponent(pathname.slice(1))}catch{return null}if(!publicFiles.has(rel))return null;try{const file=fs.realpathSync(path.resolve(root,rel)),relative=path.relative(realRoot,file);if(path.isAbsolute(relative)||relative==='..'||relative.startsWith('..'+path.sep)||!fs.statSync(file).isFile())return null;return file}catch{return null}}
const server=http.createServer(async(req,res)=>{try{const host=req.headers.host;const allowedHosts=new Set(['127.0.0.1:'+port,'localhost:'+port]);if(!allowedHosts.has(host))return json(res,403,{ok:false,error:'Unzulässiger Host'});if(req.headers.origin&&req.headers.origin!=='http://'+host)return json(res,403,{ok:false,error:'Unzulässiger Ursprung'});let u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/'))return await api(req,res,u);const f=publicFile(u.pathname);if(!f){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':mime[path.extname(f)]||'application/octet-stream','cache-control':'no-store'});if(req.method==='HEAD')return res.end();const stream=fs.createReadStream(f);stream.on('error',()=>res.destroy());stream.pipe(res)}catch(e){json(res,e.status||500,{ok:false,error:safeError(e.message)})}}).listen(port,'127.0.0.1',()=>console.log('Kommandozentrale auf http://127.0.0.1:'+port));
let shuttingDown=false;function shutdown(){if(shuttingDown)return;shuttingDown=true;tasksService.stop();for(const p of runningProcesses){if(p.connected)p.send({type:'stop'},()=>{});else p.kill()}for(const job of loginJobs.values())job.process?.kill();server.close(()=>store.close());server.closeAllConnections()}process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);process.on('exit',()=>store.close());server.on('error',error=>{store.close();console.error(safeError(error.message));process.exitCode=1});
