import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),port=process.env.PORT||3000;
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))};
const body=req=>new Promise((ok,no)=>{let d='';req.on('data',c=>{d+=c;if(d.length>1e6)req.destroy()});req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){no(e)}})});
const run=(cmd,args=[],cwd=root,timeout=15000)=>new Promise(resolve=>{let p=spawn(cmd,args,{cwd,env:{...process.env,ANTHROPIC_API_KEY:''},shell:false}),out='',err='',done=false;let finish=r=>{if(done)return;done=true;clearTimeout(timer);try{p.kill('SIGTERM')}catch{}resolve(r)};p.stdout?.on('data',d=>out+=d);p.stderr?.on('data',d=>err+=d);p.on('error',e=>finish({ok:false,error:e.message,stdout:out,stderr:err}));p.on('close',code=>finish({ok:code===0,code,stdout:out,stderr:err}));let timer=setTimeout(()=>finish({ok:false,timeout:true,stdout:out,stderr:err}),timeout)});
const present=async c=>(await run('which',[c],root,3000)).ok;
const clean=s=>String(s||'').replace(/\x1B(?:[@-Z\\-_]|\[[0-?]*[ -\/]*[@-~])/g,'').replace(/\r/g,'').trim().slice(-12000);
const authText=r=>clean(String((r.stdout||'')+'\n'+(r.stderr||'')));
const loginJobs=new Map();
async function authStatus(type){if(type==='chatgpt'){if(!await present('codex'))return {installed:false,connected:false};let r=await run('codex',['login','status'],root,8000);return {installed:true,connected:r.ok,detail:authText(r)}}if(type==='claude'){if(!await present('claude'))return {installed:false,connected:false};let r=await run('claude',['auth','status'],root,8000);return {installed:true,connected:r.ok,detail:authText(r)}}return {installed:false,connected:false}}
async function aiState(){let chatgpt=await authStatus('chatgpt'),claude=await authStatus('claude');return {ok:true,paidApi:false,chatgpt:{supported:true,...chatgpt,mode:'chatgpt-plan-codex',loginAvailable:chatgpt.installed},claude:{supported:true,...claude,mode:'claude-pro-max-code',loginAvailable:claude.installed,note:'Claude bleibt optional und kann nach einem Pro/Max-Upgrade angemeldet werden.'}}}
function jobView(type){let j=loginJobs.get(type);if(!j)return {running:false,output:''};return {running:j.running,finished:j.finished,code:j.code,output:clean(j.output),started:j.started}}
async function startLogin(type){if(type==='chatgpt'){if(!await present('codex'))return {ok:false,error:'Codex CLI ist auf dem Ausführungsdienst noch nicht installiert.'};let old=loginJobs.get(type);if(old?.running)return {ok:true,type,flow:'device-auth',...jobView(type)};let job={running:true,finished:false,code:null,output:'',started:Date.now()},p=spawn('codex',['login','--device-auth'],{cwd:root,env:{...process.env,OPENAI_API_KEY:'',ANTHROPIC_API_KEY:'',NO_COLOR:'1',TERM:'dumb'},shell:false});job.process=p;loginJobs.set(type,job);p.stdout?.on('data',d=>job.output+=d);p.stderr?.on('data',d=>job.output+=d);p.on('error',e=>{job.output+='\n'+e.message;job.running=false;job.finished=true});p.on('close',code=>{job.code=code;job.running=false;job.finished=true});await new Promise(r=>setTimeout(r,1800));return {ok:true,type,flow:'device-auth',...jobView(type)}}if(type==='claude'){if(!await present('claude'))return {ok:false,error:'Claude Code ist noch nicht installiert. Die Anmeldemöglichkeit bleibt erhalten.'};let r=await run('claude',['auth','login'],root,12000);return {ok:r.ok||r.timeout,type,flow:'browser-login',output:authText(r)}}return {ok:false,error:'Unbekannter Anbieter'}}
async function api(req,res,u){if(u.pathname==='/api/health')return json(res,200,{ok:true,service:'kommandozentrale'});if(u.pathname==='/api/capabilities'){let a=await aiState();return json(res,200,{node:true,python:await present('python3'),git:await present('git'),ffmpeg:await present('ffmpeg'),claude:a.claude.installed,codex:a.chatgpt.installed,claudeConnected:a.claude.connected,codexConnected:a.chatgpt.connected,paidApi:false})}if(u.pathname==='/api/ai-status')return json(res,200,await aiState());if(u.pathname==='/api/auth/start'&&req.method==='POST'){let b=await body(req),r=await startLogin(String(b.type||''));return json(res,r.ok?200:503,r)}if(u.pathname==='/api/auth/status'){let type=String(u.searchParams.get('type')||'chatgpt'),auth=await authStatus(type);return json(res,200,{ok:true,type,...auth,...jobView(type)})}if(u.pathname==='/api/session'&&req.method==='POST'){let b=await body(req),type=String(b.type||''),s=await authStatus(type==='codex'?'chatgpt':type);if(!s.installed)return json(res,503,{ok:false,error:'Der benötigte Client ist noch nicht installiert.'});if(!s.connected)return json(res,401,{ok:false,error:'Noch nicht angemeldet. Bitte zuerst die Anmeldung in der Kommandozentrale starten.'});return json(res,200,{ok:true,type})}return json(res,404,{ok:false,error:'Nicht gefunden'})}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.md':'text/markdown; charset=utf-8'};
http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/'))return await api(req,res,u);let rel=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1)),f=path.resolve(root,rel);if(!f.startsWith(root)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':mime[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(res)}catch(e){json(res,500,{ok:false,error:e.message})}}).listen(port,()=>console.log('Kommandozentrale auf Port '+port));