const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'.kz-test-unit-'+randomUUID());
const tick=()=>new Promise(r=>setTimeout(r,10));
(async()=>{
 const {TaskStore,redactSecrets}=await import('../task-store.js');const {TaskService,codexArguments,parseExecution}=await import('../task-service.js');
 let store=new TaskStore(root,path.relative(root,dir)),calls=0,reply={ok:true,code:0,stdout:JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'real response fixture'}})};
 let captured;const service=new TaskService({store,root,authStatus:async()=>({connected:true,detail:'Logged in using ChatGPT'}),run:async(...args)=>{calls++;captured=args;return reply}});
 const wait=async id=>{for(let n=0;n<500;n++){if(['done','error'].includes(service.get(id).state))return service.get(id);await tick()}throw Error('Test timed out: '+id+' / '+service.get(id).state)};
 let row=await service.create({id:'normal',text:'--help; echo injection',worker:'chatgpt'});assert.equal(row.state,'wait');row=await wait(row.id);assert.equal(row.state,'done');assert.deepEqual(row.history.map(h=>h.state),['wait','work','done']);assert.ok(row.startedAt&&row.finishedAt);
 assert.equal(captured[0],'codex');assert.equal(captured[1].at(-2),'--');assert.equal(captured[1].at(-1),'--help; echo injection');assert.equal(captured[3],120000);
 await service.create({id:'normal',text:'--help; echo injection'});await tick();assert.equal(calls,1);
 await assert.rejects(service.create({id:'normal',text:'different'}),/ID bereits/);
 for(const id of ['../bad','%2f','bad/name','x'.repeat(81)])await assert.rejects(service.create({id,text:'x'}));
 await assert.rejects(service.create({id:'large',text:'x'.repeat(12001)}));
 const secret='sk-'+('a'.repeat(24));await assert.rejects(service.create({id:'secret',text:secret}));await assert.rejects(service.create({id:secret,text:'ordinary text'}));assert.equal(redactSecrets(secret),'[entfernt]');
 console.log('PASS argument isolation / fixed CLI / duplicate prevention / validation / secret rejection / lifecycle');
 row=await service.create({id:'approval',text:'edit project fixture',mode:'workspace-write'});assert.equal(row.state,'wartet_auf_freigabe');const before=calls;await tick();assert.equal(calls,before);
 assert.throws(()=>service.approve('approval',false));service.approve('approval',true);service.approve('approval',true);row=await wait('approval');assert.equal(calls,before+1);assert.ok(row.approvedAt);assert.deepEqual(row.history.map(h=>h.state),['wartet_auf_freigabe','wait','work','done']);
 const args=codexArguments('workspace-write',root,'text',store.dir);assert.ok(args.includes('default_permissions="kz_project"'));const profile=args.find(a=>a.startsWith('permissions.kz_project='));assert.match(profile,/network=\{enabled=false\}/);assert.ok(profile.includes(JSON.stringify(root)+'="write"'));assert.ok(profile.includes(JSON.stringify(store.dir)+'="read"'));
 assert.ok(!args.includes('--dangerously-bypass-approvals-and-sandbox'));console.log('PASS mandatory approval / exactly once / restrictive workspace options');
 reply={ok:false,code:1,stdout:JSON.stringify({type:'item.completed',item:{type:'agent_message',text:'do not accept'}}),stderr:'process failed'};await service.create({id:'failure',text:'fail'});assert.equal((await wait('failure')).state,'error');assert.equal(service.get('failure').result,'');
 reply={ok:false,timeout:true,stdout:''};await service.create({id:'timeout',text:'timeout'});assert.match((await wait('timeout')).error,/Zeitüberschreitung/);
 reply={ok:true,stdout:JSON.stringify({type:'turn.failed',error:{message:'turn failure'}})};await service.create({id:'turn',text:'turn failed'});assert.equal((await wait('turn')).state,'error');
 reply={ok:true,stdout:''};await service.create({id:'empty',text:'empty'});assert.equal((await wait('empty')).state,'error');
 await service.create({id:'claude',text:'unavailable',worker:'claude'});assert.equal((await wait('claude')).state,'error');
 assert.equal(parseExecution({ok:true,stdout:[{type:'item.completed',item:{type:'agent_message',text:'commentary'}},{type:'item.completed',item:{type:'agent_message',text:'final'}}].map(JSON.stringify).join('\n')}),'final');
 console.log('PASS failed process / timeout / failed turn / empty response / unavailable Claude');
 service.stopped=true;await service.create({id:'interrupted',text:'restart'});store.jobs.get('interrupted').state='work';store.jobs.get('interrupted').startedAt=new Date().toISOString();store.save();
 assert.throws(()=>new TaskStore(root,path.relative(root,dir)),/bereits/);store.close();store=new TaskStore(root,path.relative(root,dir));assert.equal(store.jobs.get('normal').result,'real response fixture');assert.equal(store.jobs.get('failure').state,'error');assert.equal(store.jobs.get('interrupted').state,'error');assert.equal(store.jobs.get('interrupted').done,false);store.close();
 assert.throws(()=>new TaskStore(root,'../escape'),/im Projekt/);
 console.log('PASS durable success/failure / restart interrupts work / one store owner / storage path containment');
})().catch(e=>{console.error(e.message);process.exitCode=1}).finally(()=>{if(path.dirname(dir)===root&&path.basename(dir).startsWith('.kz-test-unit-'))fs.rmSync(dir,{recursive:true,force:true})});
